name: video_player_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  video_player: ^2.4.7
  get: ^4.6.5
  hexcolor: ^3.0.1
  audio_video_progress_bar: ^0.11.0
  flutter_custom_dialog: ^1.3.0
  flutter_pin_code_fields: ^1.1.0
  pin_code_fields: ^7.4.0
  audioplayers: ^1.1.1
  animate_do: ^2.1.0
  on_audio_query: ^2.6.1
  just_audio: ^0.9.30
  rxdart: ^0.27.6
  assets_audio_player: ^3.0.5
  flutter_share: ^2.0.0
  file_picker: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/menu/
    - assets/icons/home/
    - assets/icons/site/
    - assets/icons/music/
    # - assets/newicons/
  #   - images/a_dot_ham.jpeg
